version: "3"
services:

  databasePetProject:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=books
    volumes:
      - ./database/postgres/data:/var/lib/postgresql/data

  pgAdminPetProject:
    image: dpage/pgadmin4
    depends_on:
      - databasePetProject
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8080:80"

networks:
  default:
    driver: bridge